name: Tests and Checks
env:
  NODE_NO_WARNINGS: true
on:
  push:
    branches:
      - 'main'
  pull_request:
    paths-ignore:
      - 'website/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          standalone: true

      - name: Install Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version-file: '.node-version'

      - name: Setup Deno Runtime
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x

      - name: Get pnpm store path
        id: pnpm-store
        run: echo "store_path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Cache pnpm
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-store-graphql-v16-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-graphql-v16-

      - name: Install Dependencies
        run: pnpm i --no-frozen-lockfile # no frozen-lockfile because we change the resolutions

      - name: Prettier
        run: pnpm prettier:check

      - name: Lint
        run: pnpm lint
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'
          NODE_NO_WARNINGS: true

      - name: Build Packages
        run: pnpm build

      - name: Typecheck
        run: pnpm run check

      - name: Test ESM & CJS exports integrity
        run: pnpm bob check

      - name: ESM Integration test
        run: pnpm --filter example-node-esm run test

  unit:
    name: unit / nodejs v${{ matrix.node-version }} / graphql v${{ matrix.graphql-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 26]
        graphql-version: ['15.10.1', '16.12.0']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          standalone: true

      - name: Install Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get pnpm store path
        id: pnpm-store
        run: echo "store_path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Cache pnpm
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.local/share/pnpm/store
          key:
            ${{ runner.os }}-pnpm-store-graphql-v${{ matrix.graphql-version }}-${{
            hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-graphql-v${{ matrix.graphql-version }}-

      - name: Set GraphQL Version
        run: node scripts/override-graphql-version.js ${{ matrix.graphql-version }}

      - name: Install Dependencies
        run: pnpm i --no-frozen-lockfile # no frozen-lockfile because we change the resolutions

      - name: Build Packages
        run: pnpm build

      - name: Run Unit Tests
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: pnpm run test:unit --ci

      - name: Run Leak Tests
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          timeout_minutes: 120
          max_attempts: 3
          command: pnpm run test:unit:leaks --ci

  integration:
    name: integration / nodejs v${{ matrix.node-version }} / graphql v${{ matrix.graphql-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 26]
        graphql-version: ['15.10.1', '16.12.0']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          standalone: true

      - name: Install Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get pnpm store path
        id: pnpm-store
        run: echo "store_path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Cache pnpm
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.local/share/pnpm/store
          key:
            ${{ runner.os }}-pnpm-store-graphql-v${{ matrix.graphql-version }}-${{
            hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-graphql-v${{ matrix.graphql-version }}-

      - name: Set GraphQL Version
        run: node scripts/override-graphql-version.js ${{ matrix.graphql-version }}

      - name: Install Dependencies
        run: pnpm i --no-frozen-lockfile # no frozen-lockfile because we change the resolutions

      - name: Install Playwright Binaries
        uses: ./.github/actions/install-playwright-binaries

      - name: Build Packages
        run: pnpm build

      - name: Run Integration Tests
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: >-
            if [ "${{ matrix.node-version }}" = "18" ]; then
              pnpm test:integration --ci \
                --testPathIgnorePatterns='/(browser|sveltekit|defer-stream)\.spec\.ts$' &&
              NODE_OPTIONS=--experimental-vm-modules pnpm test:integration --ci \
            packages/plugins/defer-stream/__integration-tests__/defer-stream.spec.ts \
            packages/graphql-yoga/__integration-tests__/browser.spec.ts \
            examples/sveltekit/__integration-tests__/sveltekit.spec.ts; else
              pnpm test:integration --ci;
            fi

      - name: Run Leak Tests
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: >-
            if [ "${{ matrix.node-version }}" = "18" ]; then
              pnpm test:integration:leaks --ci \
                --testPathIgnorePatterns='/(browser|sveltekit)\.spec\.ts$'; else
              pnpm test:integration:leaks --ci;
            fi

  apollo-federation-compatibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          standalone: true
      - name: Install Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version-file: '.node-version'
      - name: Get pnpm store path
        id: pnpm-store
        run: echo "store_path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      - name: Cache pnpm
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-store-graphql-v16-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-graphql-v16-
      - name: Install Dependencies
        run: pnpm i --no-frozen-lockfile
      - name: Build Packages
        run: pnpm build
      - name: Bundle Apollo Federation Subgraph Example
        run: pnpm --filter=example-apollo-federation-compatibility build
      - name: Install Rover
        run: curl -sSL https://rover.apollo.dev/nix/latest | sh
      - name: Add Rover to PATH
        run: echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Apollo Federation Subgraph Compatibility
        uses: apollographql/federation-subgraph-compatibility@b6981fd83d24450a7cbd2d7727196e0ba57614e0 # v2
        with:
          workingDirectory: examples/apollo-federation-compatibility
          compose: docker-compose.yaml
          schema: schema.graphql
          path: /graphql
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          failOnWarning: true
          failOnRequired: true
          debug: true

  e2e:
    strategy:
      fail-fast: false
      matrix:
        plan:
          - 'aws-lambda'
          # - 'azure-function'
          - 'cf-worker'
          # - 'vercel-function' # Disabled because vercel API is not actually documented
          - 'docker-node'
          - 'cf-modules'
    name: e2e / ${{ matrix.plan }}

    runs-on: ubuntu-latest
    if:
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name ==
      github.repository && github.actor != 'dependabot[bot]' && github.actor !=
      'copilot-swe-agent[bot]' && github.actor != 'github-copilot[bot]'
    env:
      # CloudFlare
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      # Azure
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # AWS
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      # Vercel
      VERCEL_AUTH_TOKEN: ${{ secrets.VERCEL_AUTH_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          standalone: true

      - name: Install Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version-file: '.node-version'

      - name: Get pnpm store path
        id: pnpm-store
        run: echo "store_path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Cache pnpm
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-store-graphql-v16-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-graphql-v16-

      - name: Install Dependencies
        run: pnpm i --no-frozen-lockfile # no frozen-lockfile because we change the resolutions

      - name: Build Packages
        run: pnpm build

      - name: Install pulumi
        uses: pulumi/setup-pulumi@b374ceb6168550de27c6eba92e01c1a774040e11 # v2

      - name: Set outputs
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "docker_host=$(docker context inspect --format '{{.Endpoints.docker.Host}}')" >> $GITHUB_OUTPUT

      - name: Provision & Test
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        env:
          TEST_PLAN_NAME: ${{ matrix.plan }}
          COMMIT_ID: ${{ steps.vars.outputs.sha_short }}
        with:
          timeout_minutes: 10
          max_attempts: 10
          command: cd e2e && pnpm start
          retry_wait_seconds: 30

      - name: Ensure Deletion
        working-directory: e2e
        if: always()
        run: pnpm start
        env:
          ENSURE_DELETION: 1
          TEST_PLAN_NAME: ${{ matrix.plan }}
          COMMIT_ID: ${{ steps.vars.outputs.sha_short }}

  dependencies:
    if:
      github.event_name == 'pull_request' && github.event.pull_request.title != 'Upcoming Release
      Changes' && github.actor != 'dependabot[bot]' && github.actor != 'copilot-swe-agent[bot]' &&
      github.actor != 'github-copilot[bot]'
    name: Dependencies
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-dependencies
      cancel-in-progress: true
    uses: the-guild-org/shared-config/.github/workflows/changesets-dependencies.yml@v1
    with:
      node-version-file: .node-version
    secrets:
      githubToken: ${{ secrets.BOT_GITHUB_TOKEN }}
