name: Website Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  WEBSITE_CLOUDFLARE_API_TOKEN: ${{ secrets.WEBSITE_CLOUDFLARE_API_TOKEN }}

jobs:
  deployment:
    runs-on: ubuntu-latest
    if:
      github.event_name == 'push' || (github.event.pull_request.head.repo.full_name ==
      github.repository && github.actor != 'dependabot[bot]' && github.actor !=
      'copilot-swe-agent[bot]' && github.actor != 'github-copilot[bot]')
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          standalone: true

      - name: Install Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version-file: '.node-version'

      - name: Get pnpm store path
        id: pnpm-store
        run: echo "store_path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Cache pnpm
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-store-graphql-v16-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-graphql-v16-

      - name: Install Dependencies
        run: pnpm i --no-frozen-lockfile # no frozen-lockfile because we change the resolutions

      - uses: the-guild-org/shared-config/website-cf@main
        name: build and deploy website
        if: ${{ env.WEBSITE_CLOUDFLARE_API_TOKEN }}
        env:
          NEXT_BASE_PATH: ${{ github.ref == 'refs/heads/main' && '/graphql/yoga-server' || '' }}
          SITE_URL:
            ${{ github.ref == 'refs/heads/main' && 'https://the-guild.dev/graphql/yoga-server' || ''
            }}
        with:
          cloudflareApiToken: ${{ secrets.WEBSITE_CLOUDFLARE_API_TOKEN }}
          cloudflareAccountId: ${{ secrets.WEBSITE_CLOUDFLARE_ACCOUNT_ID }}
          githubToken: ${{ secrets.BOT_GITHUB_TOKEN }}
          projectName: graphql-yoga
          prId: ${{ github.event.pull_request.number }}
          mainBranch: master
          websiteDirectory: ./
          buildScript: pnpm build && cd website && pnpm build
          artifactDir: website/out
